/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // main: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  main: [
    "introduction",
    "glueops-cluster-domain",
    {
      type: "category",
      label: "Pre-Deployment Setup",
      collapsible: false,
      items: [
        "predeployment/github-oauth",
        "predeployment/github-app",
      ],
      link: {
        type: "generated-index",
        title: "Pre-Deployment Setup",
        description: "Before deploying your cluster, you need to create your GitHub OAuth App and GitHub App. These apps will provide the necessary values for secure access, authentication, and automated deployments on GlueOps.",
        slug: "/predeployment",
      },
    },
    "glueops-deployment-configuration",
    'deploy-hello-world-to-glueops',
    'deploy-docusarus-website-to-glueops'
  ],
};

module.exports = sidebars;
